# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'gabriei/api-producao1'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
    buildContext: '.'
    tags:  | 
        $(build.BuildId)
        latest

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Producao(de94d3f1-d937-41f6-b44c-6b665311b1f1)'
    appType: 'webAppContainer'
    WebAppName: 'DeployAppAzure'
    DockerNamespace: 'gabriei'
    DockerRepository: 'api-producao1'
    DockerImageTag: '$(build.BuildId)'
        

